//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTest.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectionDetail
    {
        public int Id { get; set; }
        public int Collection_Id { get; set; }
        public string Food_Name { get; set; }
    
        public virtual Collection Collection { get; set; }
    }
}
