//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTest.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collection
    {
        public Collection()
        {
            this.CollectionDetails = new HashSet<CollectionDetail>();
        }
    
        public int Id { get; set; }
        public int Restaurant_Id { get; set; }
        public Nullable<int> Employee_Id { get; set; }
        public string Status { get; set; }
        public System.DateTime Preserved_Time { get; set; }
    
        public virtual ICollection<CollectionDetail> CollectionDetails { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
