//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTest.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurant
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Restaurant_Type { get; set; }
        public string Location { get; set; }
        public int User_Id { get; set; }
        public string Picture { get; set; }
    
        public virtual User User { get; set; }
    }
}
